### PR TITLE
Java 7 and Tomcat 8 support + AWS SDK updated

### PR DESCRIPTION
**Pull request by imdario**
In order to keep this project working on the latest versions of Java and Tomcat's available packages, I created this pull request.

### CODE REVIEW

**Comment by imdario** [comment]
Ok, this pull is good to go, the strange behavoir was a quirk of our code on Java 8 (boxing/unboxing issues). It should be noted that it wasn't tested on Tomcat 7.

**Comment by hanshuo-aws** [comment]
We have accepted pull request #16 which updates the SDK dependency.

For the Tomcat 8 changes, I believe they are not backwards-compatible with Tomcat 7, since getContext() was not added until Tomcat 8. We can't accept this change and then break all the Tomcat 7 users.
Should we instead create another branch for Tomcat 8 support? (and also use a different maven version there?)

**Comment by imdario** [comment]
You are right, Tomcat 8 changes are not backwards-compatible. I'm sorry to have introduced a non compatible modification. We should create another branch for Tomcat 8 support.

**Comment by hyandell** [comment]
Wouldn't you create a Tomcat 7 legacy branch, that over time can be deprecated when Tomcat 7 reaches end of life?

**Comment by fulghum** [comment]
Good suggestion Henri.  We should spin up a tomcat-7 branch for the current code and move on to Tomcat 8 for the master branch.

**Comment by imdario** [comment]
:+1: It is a really good idea.

**Comment by shorea** [comment]
We are accepting this pull request with a few modifications to preserve backwards compatibility with Tomcat 7. Thanks for the contribution

**Comment by shorea** [comment]
https://github.com/aws/aws-dynamodb-session-tomcat/releases/tag/v1.0.4

**Comment by imdario** [comment]
Thanks! Today I planned to do more Tomcat DynamoDB sessions' testing and your message arrived at the perfect time.

**Comment by Selindek** [comment]
During you test try to modify some data in the stored session. After 30 seconds the changes will be lost....

**Comment by shorea** [comment]
Selindek, how consistenly are you seeing this behavior?

**Comment by shorea** [comment]
Tried it with the current and the previous release and seeing the issue sporadically in both. This seems to be the same issue pointed out in your pull request #19, correct?

**Comment by Selindek** [comment]
Yes that's the same issue. But it happened continuously in our system. That's why I created my version. We use my version on a live server for more than a month and there are no any problems.
If you want to reproduce the issue for sure, do the following: 
create a session 
wait a minute to make sure the session is stored in the DB.
modify a data in the session.
wait at least 30 seconds. (Idle tests run in every 30 seconds by default)
... the old version will be loaded back from the DB

**Pull request merged**
